export const ROUTES = {
    HOME: "/",
    RESOURCES: "/resources",
    OVERVIEW: "/overview",
    PRICING: "/pricing",
    MODELS: "/models",
    ENTERPRISE: "/enterprise",
    NOT_FOUND: "*",
    FAQ: "/faq",
    TEST_AI: "/test-ai",
    ABOUT: "/about",
    CONTACT: "/contact",
    SIGN_IN: "/api/auth/signin/",
    SALES: "/sales",
    PRIVACY: "/privacy",
    TERMS: "/terms",
    PRODUCTS: "/products",
    AI_INTEGRATION: "/ai-integration",
    TEAM: "/team",
    SUGGEST_FEATURE: "/suggest-feature",
    DOCS: "/docs",
    BLOG: "/blog",
    PROJECT: "/project",
};
